pkg = "assets"
dest = "./pkg/assets/"
fmt = false

clean = false
output = "ab0x.go"
unexporTed = false
spread = true
debug = false

[[custom]]
files = ["./ui/public/"]
base = "./ui/public/"
exclude = [".DS_Store"]
